name: flutter_app_scaffold
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^13.2.0
  provider: ^6.0.5
  dio: ^5.3.2
  flutter_secure_storage: ^8.0.0
  url_launcher: ^6.3.2
  file_picker: ^10.2.0
  table_calendar: ^3.0.8
  intl: ^0.18.1
  open_filex: 4.7.0
  fl_chart: ^0.68.0
  timeago: ^3.6.0
  uuid: ^4.3.3
  image_picker: ^1.0.8
  shared_preferences: ^2.0.12
  path_provider: ^2.1.0
  flutter_launcher_icons: "^0.13.1" 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.jpg
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/docs/
    - assets/images/
    - assets/logo.jpg
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.jpg"
  min_sdk_android: 21 