// firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCass5zgKUOxAw_ClcmhZY-aU0OcSYtJ6Y',
    appId: '1:1087984389795:web:716c8df1e1667ad3eff916',
    messagingSenderId: '1087984389795',
    projectId: 'environmental-safety-app',
    authDomain: 'environmental-safety-app.firebaseapp.com',
    storageBucket: 'environmental-safety-app.firebasestorage.app',
    measurementId: 'G-PH1N29VK6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXNdBca7dbMmJ4SqyJFrwixBPcXeE5uKc',
    appId: '1:1087984389795:android:669482ea4154607feff916',
    messagingSenderId: '1087984389795',
    projectId: 'environmental-safety-app',
    storageBucket: 'environmental-safety-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5EYly4WB30l-VF_qrAKa5w4jW5P0_aBY',
    appId: '1:1087984389795:ios:e56f97cf0f69986deff916',
    messagingSenderId: '1087984389795',
    projectId: 'environmental-safety-app',
    storageBucket: 'environmental-safety-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppScaffold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5EYly4WB30l-VF_qrAKa5w4jW5P0_aBY',
    appId: '1:1087984389795:ios:e56f97cf0f69986deff916',
    messagingSenderId: '1087984389795',
    projectId: 'environmental-safety-app',
    storageBucket: 'environmental-safety-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppScaffold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCass5zgKUOxAw_ClcmhZY-aU0OcSYtJ6Y',
    appId: '1:1087984389795:web:b59161d612442f8eeff916',
    messagingSenderId: '1087984389795',
    projectId: 'environmental-safety-app',
    authDomain: 'environmental-safety-app.firebaseapp.com',
    storageBucket: 'environmental-safety-app.firebasestorage.app',
    measurementId: 'G-0RH3DWM10H',
  );

}